server:
  port: 8090
spring:
  ai:
    dashscope:
      api-key: sk-f9ca25f37aa249f9a67feaf36113ab34
      chat:
        options:
#          model: deepseek-v3.2
          model: glm-4.7
#          model: qianwen-v3.2
    # 配置向量存储
    vectorstore:
      simple:
        # 使用简单的内存向量存储
        enabled: true
    # 配置embedding
    embedding:
      dashscope:
        api-key: sk-f9ca25f37aa249f9a67feaf36113ab34
        options:
          model: text-embedding-v2
