server:
  port: 8090
spring:
  ai:
    # Milvus 向量数据库配置
    vectorstore:
      milvus:
        client:
          host: "10.1.7.208"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "sjt"
        collectionName: "vector_store"
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE

    dashscope:
      api-key: sk-f9ca25f37aa249f9a67feaf36113ab34
      chat:
        options:
#          model: deepseek-v3.2
          model: glm-4.7
#          model: qianwen-v3.2


# 会话存储路径配置，默认使用用户主目录下的 .chat-assistant/sessions
session-storage-path: D:\sessions
